version: '3.9'

volumes:
  minio-data: {}

services:
  database:
    image: quay.io/minio/minio
    restart: always
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9090"
    ports:
      - ${MINIO_CONSOLE_PORT}:9090
    environment:
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD
    healthcheck:
        test: ["CMD", "curl", "-f", "http://database:9000/minio/health/live"]
        interval: 30s
        timeout: 20s
        retries: 3

  app:
    build:
      context: ./FileShare
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - database
    ports:
      - ${APP_PORT}:80
    profiles:
      - Production

    environment:
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD
      - MINIO_PORT
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
      - ASPNETCORE_URLS=http://+:80
      - DOTNET_USE_POLLING_FILE_WATCHER=1

  dev-app:
    extends:
      service: app
    build:
      context: ./FileShare
      dockerfile: ${ENVIRONMENT}.Dockerfile
    profiles:
      - Development
    volumes:
      - ./FileShare:/app
      - ~/.nuget/packages:/root/.nuget/packages