version: '3.9'

volumes:
  minio-data: {}

services:
  database:
    image: quay.io/minio/minio
    restart: always
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9090"
    ports:
      - 9000:9000
      - 9090:9090
    environment:
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD
    healthcheck:
        test: ["CMD", "curl", "-f", "http://database:9000/minio/health/live"]
        interval: 30s
        timeout: 20s
        retries: 3

  app:
    build:
      context: ./FileShare
    restart: always
    depends_on:
      - database
    ports:
      - 80:80
      - 443:80

    environment:
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80