name: Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deployment using ssh
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          cd ${{ github.event.repository.name }}
          git pull
          docker compose down
          APP_PORT=${{ secrets.APP_PORT }}
          MINIO_ROOT_USER=${{ secrets.MINIO_USER }}
          MINIO_ROOT_PASSWORD=${{ secrets.MINIO_PASSWORD }}
          MINIO_CONSOLE_PORT=${{ secrets.MINIO_CONSOLE_PORT }}
          docker compose up -d --build
          docker builder prune
